boardgamelogger/boardgamelogger/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('gameCollections/', include('gameCollections.urls')),
    path('gamefinders/', include('gamefinders.urls')),
    path('games/', include('games.urls')),
    path('admin/', admin.site.urls),
]

boardgamelogger/gameCollections/urls.py
from django.urls import path

from . import views

urlpatterns = [
        # ex: /gamecollections/
        path('', views.index, name='index'),

        # ex: /gameCollections/1/
        path('<int:collection_id>/', views.gameCollectionView, name='detail'),
        ]

boardgamelogger/gamefinders/urls.py
from django.urls import path

from . import views

urlpatterns = [
        path('', views.index, name='index')
        ]

boardgamelogger/games/urls.py
from django.urls import path

from . import views

app_name = 'games'

urlpatterns = [
        # ex: /games/
        path('', views.index, name='index'),

        # ex: /games/1/
        path('<int:game_id>/', views.gameDetail, name='detail'),

        # ex: /games/1/vote
        path('<int:game_id>/vote/', views.vote,name='vote'),
        ]

boardgamelogger/gameCollections/models.py
from django.db import models

class gameCollection(models.Model):
    collection_name = models.CharField(max_length=200)
    collection_started_date = models.DateTimeField('date created', auto_now_add=True)
    # collection_owner
    # collection_num_gamesj
    # collection_most_recent_addition_date

    def __str__(self):
        return self.collection_name

boardgamelogger/gamefinders/models.py
from django.db import models

# Create your models here.

boardgamelogger/games/models.py
import datetime

from django.db import models
from django.utils import timezone

from gameCollections.models import gameCollection


class Game(models.Model):
    game_collection = models.ForeignKey(
            gameCollection,
            on_delete=models.CASCADE)
    game_title = models.CharField(max_length=200)
    game_publisher = models.CharField(max_length=200)
    game_bgg_url = models.CharField(max_length=200)
    game_pub_date = models.DateTimeField('date published', blank=True)
    game_added_date = models.DateTimeField('date published', auto_now_add=True, blank=True)

    def __str__(self):
        return self.game_title

    def was_added_recently(self):
        return self.game_added_date >= timezone.now() - datetime.timedelta(days=1)

boardgamelogger/gameCollections/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
# from django.template import loader

from .models import gameCollection

def index(request):
    
    latest_game_collections_list = gameCollection.objects.order_by('-collection_started_date')[:5]

    # template = loader.get_template('gameCollections/index.html')
    context = {'latest_game_collections_list': latest_game_collections_list, }
    
    return render(request, 'gameCollections/index.html', context)

def gameCollectionView(request, collection_id):
    try:
        collection = gameCollection.objects.get(pk=collection_id)
    except gameCollection.DoesNotExist:
        raise Http404("That game collection does not exist")
    return render(request, 'gameCollections/detail.html', {'collection': collection})

boardgamelogger/gamefinders/views.py
from django.shortcuts import render
# from django.http import HttpResponse

def index(request):
    return render(request, 'gamefinders/index.html')

boardgamelogger/games/views.py
from django.shortcuts import render, get_object_or_404

from .models import Game

def index(request):
    
    latest_games_list = Game.objects.order_by('-game_added_date')[:5]

    context = {'latest_games_list': latest_games_list, }
    
    return render(request, 'games/index.html', context)

def gameDetail(request, game_id):
    game = get_object_or_404(Game, pk=game_id)

    return render(request, 'games/detail.html', {'game': game})

boardgamelogger/gameCollections/templates/gameCollections/detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>gameCollection Detail Page</title>
    </head>
<body>
    {{ collection }}
</body>
</html>

boardgamelogger/gameCollections/templates/gameCollections/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>gameCollection Index Page</title>
    </head>
    <body>
        {% if latest_game_collections_list %}
        <ul>
        {% for gameCollection in latest_game_collections_list %}
            <li><a href="/gameCollections/{{ gameCollection.id }}/">{{ gameCollection.collection_name }}</a></li>
        {% endfor %}
        </ul>
        {% else %}
        <p>No game collections are available.</p>
        {% endif %}
    </body>
</html>

boardgamelogger/gamefinders/templates/gamefinders/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>gameFinders Index Page</title>
  </head>
<body>
  <h1>The Game Finder</h1>
  <p>Click the "Submit" button to help catalog your desired game".</p>
  <form action="/action_page.php">
    <label for="gameURL">game URL:</label>
    <input type="text" id="gameURL" name="gameURL"><br><br>
    <input type="submit" value="Submit">
  </form>
</body>
</html>

boardgamelogger/games/templates/games/detail.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title>Game Detail Page</title>
    </head>

    <body>
        <h1>{{ game.game_title }}</h1>  
        <ul>
            <!-- {#% for detail in game %#} -->
            <li>Publisher: {{ game.game_publisher }}</li>
            <li>BGG URL: {{ game.game_bgg_url }}</li>
            <li>Published Date:{{ game.game_pub_date }}</li>
            <li>Added to Site Date: {{ game.game_added_date }}</li>
        </ul>
        <br>
        <form action="{% url 'games:detail' game.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ game.game_title }} Rating</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in '0123456789'|make_list %}
                <input type="radio" name="rating" id="rating{{ forloop.counter }}" value="{{ choice }}">
                <label for="choice{{ forloop.counter }}">{{ choice }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
        </form>
    </body>

</html>

boardgamelogger/games/templates/games/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title> Game Index Page</title>
    </head>
    <body>
        {% if latest_games_list %}
            <ul>
            {% for game in latest_games_list %}
                <li>
                    <a href="{% url 'games:detail' game.id %}">{{ game.game_title }}</a>
                </li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No games are available.</p>
        {% endif %}
    </body>
</html>